/* 
/* nomeSubestacao
    local
    email
    dataFiscalizacao
    tipoEstacao
    nivelTensao
    potenciaTransfQdeEntLT
    potenciaTransfQdeSaiLT
    potenciaTransfNivTensEntrLT
    potenciaTransfNivTensSaiLT
    verificacaoAtualizacaoDiagramaUnifiliar
    descricaoVerificacao
    equipNivelCurtCircuit
    equipNivelIsolamento
    equipVidaUtil
    equipTempoInstalacao
    paraRaiosTempConexEletrica
    paraRaiosMaterial
    bobinasBloqueioTempConexEletrica
    bobinBloqueioCondiConservaCxaComunicaC
    TPsTemperatConexElect
    TPsTipo
    TCsTemperatConexElect
    TCsTipo
    chavesTemperatConexElect
    chavesTipoAberturA
    chavesTipo
    chavesCxa
    chavesTensNominal
    chavesCorrenteNominal
    disjuntoresTemperatConexElect
    disjuntoresMecanismo
    disjuntoresPainel
    disjuntorSistemaDisparador
    trfo1Tipo
    trfo1Ausencia
    trfo1Verificacao
    trfo1Saturacao
    trfo1VerificacaoTemperatura
    trfo1NivelRuído
    trfo1PotenciaNominal
    trfo1TipoIsolação
    trfo1EstadoConservação
    trfo1AusenciaPontos
    trfo1PlacaInformações
    trfo1FechamentoEnrolamentos
    trfo1ExistnciaComutador
    trf2Impedancia
    trf2AusenciaVazamento
    trf2Saturacao
    trf2VerificacaoTemperatura
    trfo2NivelRuído
    trfo2PotenciaNominal
    trfo2TipoIsolação
    trfo2EstadoConservação
    trfo2AusenciaPontos
    trfo2PlacaInformações
    trfo2FechamentoEnrolamentos
    trfo2ExistnciaComutador
    bancoCapacitoresNivelTensao
    bancoCapacitoresPotnciaCelula
    bancoCapacitoresPotenciaBanco
    bancoCapacitoresTipoMaterIsolante
    TipoLigBancoCapacitores
    reatores
    tipoDiscoQtdIsoladores
    tipoDiscoMaterial
    tipoColunaQtdIsoladores
    tipoColunaMaterial
    muflas
    cubiculos
    paineisComandControle
    paineisProtec
    paineisSoftware
    paineisComunicacProtec
    paineisComunicaRemota
    paineisEstadoConserva
    paineisConexAdequada
    equipamentosServicosAuxTransformadores
    equipamentosServicosAuxPainel
    equipamentosServicosAuxSalaConjunto
    equipamentosServicosAuxLavaolhos
    equipamentosServicosAuxVentilacao
    equipamentosServicosAuxCarregador
    equipamentosServicosAuxAusencia
    equipamentosServicosAuxGerador
    cablagemVerificacaoConservacao
    cablagemVerificacaoSuficiente
    aterramentoProtecaoConntraDescargasAtmosfericas
    arranjoEletromecanico
    arranjoEletromecanicoTipoManobra
    arranjoEletromecanicoVL1
    arranjoEletromecanicoVL2
    arranjoEletromecanicoVerificarCondicoes
    arranjoEletromecanicoPintura
    arranjoEletromecanicoAusenciaCorrosao
    arranjoEletromecanicoETD
    arranjoEletromecanicoRelatos
    arranjoEletromecanicoVerificacaoConexoseltricas
    arranjoEletromecanicoQtdPontos
    arranjoEletromecanicoMaiortemperatura
    arranjoEletromecanicoVerificarEstado
    arranjoEletromecanicoDisponibilidade
    arjoEletromecanicoVerificEstadConserva
    arranjoEletromecanicoVerifOcorrencia
    arranjoEletromecanicoAusenciaTampa
    arranjoEletromecanicoIstadoConserva
    arranjoEletroVerifAdequacao
    arranjoEletroVerificDistancias
    arranjoEletroExistencia
    arranjoEletroCaixa
    testFuncionamento
    testManobra
    testManobraDisjuntores
    testPartida
    testComissionamento
    testRel
    testRuido
    testTemperatura
    consInfraMuro
    consInfraConcertina
    consInfraPlacaETD
    consInfraPlacasinalizacao
    consInfraEntorno
    consInfraAterramento
    consInfraValidade
    consInfraDisponibilidade
    consInfraAusencia
    consInfraFuncionalidade
    consInfraAdequacaoAcomodacoes
    consInfraExistenciaEPCs
    consInfraPintura
    consInfraAusenciaMaFormac
    consInfraAusnciaVegetação
    consInfraMonitoramento
    consInfraNivelRuido
    consInfraAusnciaEquipament
    consInfraEquipamentOperando
} */